parserOptions:
    ecmaVersion: 2022
    sourceType: module
env:
    browser: true
    es2021: true
extends: eslint:recommended
rules:
    # https://crockford.com/code.html
    array-bracket-newline: error
    array-bracket-spacing: error
    array-element-newline: off
    arrow-parens:
        - error
        - as-needed
    arrow-spacing: error
    block-spacing: error
    brace-style: error
    comma-dangle: error
    comma-spacing: error
    comma-style: error
    computed-property-spacing: error
    dot-location: error
    eol-last: error
    func-call-spacing: error
    function-call-argument-newline: off
    function-paren-newline: off
    generator-star-spacing: error
    implicit-arrow-linebreak: error
    indent: error
    jsx-quotes: error
    key-spacing: error
    keyword-spacing: error
    line-comment-position: error
    linebreak-style: error
    lines-around-comment: off
    lines-between-class-members: off
    max-len:
        - error
        - code: 100
          ignoreUrls: true
          ignoreStrings: true
          ignoreTemplateLiterals: true
          ignoreRegExpLiterals: true
    max-statements-per-line: error
    multiline-ternary: off
    new-parens: error
    newline-per-chained-call: error
    no-extra-parens: error
    no-mixed-spaces-and-tabs: error
    no-multi-spaces: error
    no-multiple-empty-lines: error
    no-tabs: error
    no-trailing-spaces: error
    no-whitespace-before-property: error
    nonblock-statement-body-position: error
    object-curly-newline: error
    object-curly-spacing: error
    object-property-newline: off
    operator-linebreak: error
    padded-blocks: off
    padding-line-between-statements: error
    quotes: error
    rest-spread-spacing: error
    semi: error
    semi-spacing: error
    semi-style: error
    space-before-blocks: error
    space-before-function-paren:
        - error
        - named: never
    space-in-parens: error
    space-infix-ops: error
    space-unary-ops: error
    switch-colon-spacing: error
    template-curly-spacing: error
    template-tag-spacing: error
    unicode-bom: error
    wrap-iife: error
    wrap-regex: error
    yield-star-spacing: error
